// Copyright 2025 The Pro Video Player Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:pro_video_player_platform_interface/src/pigeon_generated/messages.g.dart';

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is VideoSourceType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is VideoScalingModeEnum) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is SubtitleRenderModeEnum) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is ControlsModeEnum) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is CastStateEnum) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is CastDeviceTypeEnum) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is PipActionTypeEnum) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is SubtitleFormatEnum) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is CodecSupportLevelEnum) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is PlaybackStateEnum) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    } else if (value is VideoSourceMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is VideoPlayerOptionsMessage) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is PlatformInfoMessage) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is BatteryInfoMessage) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is SubtitleTrackMessage) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is AudioTrackMessage) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is VideoQualityTrackMessage) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is PipOptionsMessage) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is PipActionMessage) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is CastDeviceMessage) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is VideoMetadataMessage) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is MediaMetadataMessage) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is SubtitleSourceMessage) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is ExternalSubtitleTrackMessage) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is CodecInfoMessage) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else if (value is CodecCompatibilityMessage) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    } else if (value is VideoPlayerEventMessage) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : VideoSourceType.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : VideoScalingModeEnum.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : SubtitleRenderModeEnum.values[value];
      case 132:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ControlsModeEnum.values[value];
      case 133:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CastStateEnum.values[value];
      case 134:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CastDeviceTypeEnum.values[value];
      case 135:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PipActionTypeEnum.values[value];
      case 136:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : SubtitleFormatEnum.values[value];
      case 137:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CodecSupportLevelEnum.values[value];
      case 138:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlaybackStateEnum.values[value];
      case 139:
        return VideoSourceMessage.decode(readValue(buffer)!);
      case 140:
        return VideoPlayerOptionsMessage.decode(readValue(buffer)!);
      case 141:
        return PlatformInfoMessage.decode(readValue(buffer)!);
      case 142:
        return BatteryInfoMessage.decode(readValue(buffer)!);
      case 143:
        return SubtitleTrackMessage.decode(readValue(buffer)!);
      case 144:
        return AudioTrackMessage.decode(readValue(buffer)!);
      case 145:
        return VideoQualityTrackMessage.decode(readValue(buffer)!);
      case 146:
        return PipOptionsMessage.decode(readValue(buffer)!);
      case 147:
        return PipActionMessage.decode(readValue(buffer)!);
      case 148:
        return CastDeviceMessage.decode(readValue(buffer)!);
      case 149:
        return VideoMetadataMessage.decode(readValue(buffer)!);
      case 150:
        return MediaMetadataMessage.decode(readValue(buffer)!);
      case 151:
        return SubtitleSourceMessage.decode(readValue(buffer)!);
      case 152:
        return ExternalSubtitleTrackMessage.decode(readValue(buffer)!);
      case 153:
        return CodecInfoMessage.decode(readValue(buffer)!);
      case 154:
        return CodecCompatibilityMessage.decode(readValue(buffer)!);
      case 155:
        return VideoPlayerEventMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}
