import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:pro_video_player_platform_interface/src/container/container_parser.dart';
import 'package:pro_video_player_platform_interface/src/types/container_track_type.dart';

/// Integration tests using real FFmpeg-generated video files.
///
/// These tests verify that the parsers correctly handle real-world files
/// generated by FFmpeg with various codec combinations.
void main() {
  final fixturesDir = Directory('test/fixtures/containers');

  setUpAll(() {
    if (!fixturesDir.existsSync()) {
      fail(
        'Fixtures directory not found: ${fixturesDir.path}\n'
        'Run the fixture generation script first.',
      );
    }
  });

  group('Real file parsing', () {
    group('MP4 files', () {
      test('parses sample_h264_aac.mp4', () {
        final file = File('${fixturesDir.path}/sample_h264_aac.mp4');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final format = ContainerParser.detectFormat(data);
        expect(format, equals('mp4'));

        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('mp4'));
        expect(metadata.tracks.length, greaterThanOrEqualTo(2));

        final videoTrack = metadata.videoTracks.first;
        expect(videoTrack.type, equals(ContainerTrackType.video));
        expect(videoTrack.codec.fourcc, equals('avc1'));
        expect(videoTrack.codec.name, equals('H.264'));
        expect(videoTrack.videoInfo?.width, equals(160));
        expect(videoTrack.videoInfo?.height, equals(120));

        final audioTrack = metadata.audioTracks.first;
        expect(audioTrack.type, equals(ContainerTrackType.audio));
        expect(audioTrack.codec.fourcc, equals('mp4a'));
        expect(audioTrack.codec.name, equals('AAC'));
      });

      test('parses sample_hevc_aac.mp4', () {
        final file = File('${fixturesDir.path}/sample_hevc_aac.mp4');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final format = ContainerParser.detectFormat(data);
        expect(format, equals('mp4'));

        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('mp4'));

        final videoTrack = metadata.videoTracks.first;
        expect(videoTrack.codec.fourcc, equals('hvc1'));
        expect(videoTrack.codec.name, equals('HEVC'));
      });
    });

    group('MOV files', () {
      test('parses sample_h264.mov', () {
        final file = File('${fixturesDir.path}/sample_h264.mov');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final format = ContainerParser.detectFormat(data);
        expect(format, equals('mov'));

        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('mov'));
        expect(metadata.videoTracks.length, equals(1));
        expect(metadata.audioTracks.length, equals(1));
      });
    });

    group('M4A files', () {
      test('parses sample_audio.m4a', () {
        final file = File('${fixturesDir.path}/sample_audio.m4a');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final format = ContainerParser.detectFormat(data);
        expect(format, equals('m4a'));

        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('m4a'));
        expect(metadata.audioTracks.length, equals(1));
        expect(metadata.videoTracks.length, equals(0));

        final audioTrack = metadata.audioTracks.first;
        expect(audioTrack.codec.fourcc, equals('mp4a'));
      });
    });

    group('MKV files', () {
      test('parses sample_h264_aac.mkv', () {
        final file = File('${fixturesDir.path}/sample_h264_aac.mkv');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final format = ContainerParser.detectFormat(data);
        expect(format, equals('mkv'));

        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('mkv'));

        expect(metadata.videoTracks.length, equals(1));
        final videoTrack = metadata.videoTracks.first;
        expect(videoTrack.codec.name, equals('H.264'));
        expect(videoTrack.videoInfo?.width, equals(160));
        expect(videoTrack.videoInfo?.height, equals(120));

        expect(metadata.audioTracks.length, equals(1));
        final audioTrack = metadata.audioTracks.first;
        expect(audioTrack.codec.name, equals('AAC'));
      });

      test('parses sample_hevc_opus.mkv', () {
        final file = File('${fixturesDir.path}/sample_hevc_opus.mkv');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('mkv'));

        final videoTrack = metadata.videoTracks.first;
        expect(videoTrack.codec.name, equals('HEVC'));

        final audioTrack = metadata.audioTracks.first;
        expect(audioTrack.codec.name, equals('Opus'));
      });
    });

    group('WebM files', () {
      test('parses sample_vp9_opus.webm', () {
        final file = File('${fixturesDir.path}/sample_vp9_opus.webm');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final format = ContainerParser.detectFormat(data);
        expect(format, equals('webm'));

        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('webm'));

        final videoTrack = metadata.videoTracks.first;
        expect(videoTrack.codec.name, equals('VP9'));

        final audioTrack = metadata.audioTracks.first;
        expect(audioTrack.codec.name, equals('Opus'));
      });

      test('parses sample_vp8_vorbis.webm', () {
        final file = File('${fixturesDir.path}/sample_vp8_vorbis.webm');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('webm'));

        final videoTrack = metadata.videoTracks.first;
        expect(videoTrack.codec.name, equals('VP8'));

        final audioTrack = metadata.audioTracks.first;
        expect(audioTrack.codec.name, equals('Vorbis'));
      });
    });

    group('TS files', () {
      test('parses sample_h264_aac.ts', () {
        final file = File('${fixturesDir.path}/sample_h264_aac.ts');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final format = ContainerParser.detectFormat(data);
        expect(format, equals('ts'));

        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('ts'));
        expect(metadata.tracks.length, greaterThanOrEqualTo(1));

        // TS files should have at least video track
        final videoTrack = metadata.videoTracks.first;
        expect(videoTrack.codec.name, equals('H.264'));
      });

      test('parses sample_mpeg2_mp2.ts', () {
        final file = File('${fixturesDir.path}/sample_mpeg2_mp2.ts');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('ts'));

        final videoTrack = metadata.videoTracks.first;
        expect(videoTrack.codec.name, equals('MPEG-2'));
      });

      test('parses sample_h264_videoonly.ts', () {
        final file = File('${fixturesDir.path}/sample_h264_videoonly.ts');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('ts'));
        expect(metadata.videoTracks.length, equals(1));
        expect(metadata.audioTracks.length, equals(0));
      });
    });

    group('FLV files', () {
      test('parses sample_h264_aac.flv', () {
        final file = File('${fixturesDir.path}/sample_h264_aac.flv');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final format = ContainerParser.detectFormat(data);
        expect(format, equals('flv'));

        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('flv'));
        expect(metadata.tracks.length, greaterThanOrEqualTo(2));

        final videoTrack = metadata.videoTracks.first;
        expect(videoTrack.codec.name, equals('H.264'));
        expect(videoTrack.codec.fourcc, equals('avc1'));

        final audioTrack = metadata.audioTracks.first;
        expect(audioTrack.codec.name, equals('AAC'));
      });

      test('parses sample_h264_mp3.flv', () {
        final file = File('${fixturesDir.path}/sample_h264_mp3.flv');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('flv'));

        final audioTrack = metadata.audioTracks.first;
        expect(audioTrack.codec.name, equals('MP3'));
      });

      test('parses sample_h264_videoonly.flv', () {
        final file = File('${fixturesDir.path}/sample_h264_videoonly.flv');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('flv'));
        expect(metadata.videoTracks.length, equals(1));
        expect(metadata.audioTracks.length, equals(0));
      });
    });

    group('AVI files', () {
      test('parses sample_h264_mp3.avi', () {
        final file = File('${fixturesDir.path}/sample_h264_mp3.avi');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final format = ContainerParser.detectFormat(data);
        expect(format, equals('avi'));

        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('avi'));
        expect(metadata.tracks.length, greaterThanOrEqualTo(2));

        final videoTrack = metadata.videoTracks.first;
        expect(videoTrack.type, equals(ContainerTrackType.video));
        expect(videoTrack.codec.name, equals('H.264'));
        expect(videoTrack.videoInfo?.width, equals(160));
        expect(videoTrack.videoInfo?.height, equals(120));

        final audioTrack = metadata.audioTracks.first;
        expect(audioTrack.codec.name, equals('MP3'));
      });

      test('parses sample_mpeg4_pcm.avi', () {
        final file = File('${fixturesDir.path}/sample_mpeg4_pcm.avi');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('avi'));

        final videoTrack = metadata.videoTracks.first;
        // FFmpeg uses FMP4 fourcc which maps to "FFmpeg MPEG-4"
        expect(videoTrack.codec.name, anyOf(equals('MPEG-4'), equals('FFmpeg MPEG-4')));

        final audioTrack = metadata.audioTracks.first;
        expect(audioTrack.codec.name, equals('PCM'));
      });

      test('parses sample_mjpeg_mp3.avi', () {
        final file = File('${fixturesDir.path}/sample_mjpeg_mp3.avi');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('avi'));

        final videoTrack = metadata.videoTracks.first;
        expect(videoTrack.codec.name, equals('Motion JPEG'));
      });

      test('parses sample_xvid_videoonly.avi', () {
        final file = File('${fixturesDir.path}/sample_xvid_videoonly.avi');
        if (!file.existsSync()) {
          markTestSkipped('Fixture file not found: ${file.path}');
          return;
        }

        final data = file.readAsBytesSync();
        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull);
        expect(metadata!.format, equals('avi'));
        expect(metadata.videoTracks.length, equals(1));
        expect(metadata.audioTracks.length, equals(0));

        final videoTrack = metadata.videoTracks.first;
        expect(videoTrack.codec.name, equals('Xvid'));
      });
    });
  });

  group('Format auto-detection', () {
    test('correctly distinguishes all supported formats', () {
      final formatTests = <String, String>{
        'sample_h264_aac.mp4': 'mp4',
        'sample_hevc_aac.mp4': 'mp4',
        'sample_h264.mov': 'mov',
        'sample_audio.m4a': 'm4a',
        'sample_h264_aac.mkv': 'mkv',
        'sample_hevc_opus.mkv': 'mkv',
        'sample_vp9_opus.webm': 'webm',
        'sample_vp8_vorbis.webm': 'webm',
        'sample_h264_aac.ts': 'ts',
        'sample_mpeg2_mp2.ts': 'ts',
        'sample_h264_aac.flv': 'flv',
        'sample_h264_mp3.flv': 'flv',
        'sample_h264_mp3.avi': 'avi',
        'sample_mpeg4_pcm.avi': 'avi',
      };

      for (final entry in formatTests.entries) {
        final file = File('${fixturesDir.path}/${entry.key}');
        if (!file.existsSync()) continue;

        final data = file.readAsBytesSync();
        final format = ContainerParser.detectFormat(data);
        expect(format, equals(entry.value), reason: 'File: ${entry.key}');
      }
    });

    test('parses all fixture files without errors', () {
      final files = fixturesDir.listSync().whereType<File>().where((f) => !f.path.endsWith('.md'));

      for (final file in files) {
        final data = file.readAsBytesSync();
        final format = ContainerParser.detectFormat(data);
        expect(format, isNotNull, reason: 'Failed to detect format: ${file.path}');

        final metadata = ContainerParser.parse(data);
        expect(metadata, isNotNull, reason: 'Failed to parse: ${file.path}');
        expect(metadata!.tracks.length, greaterThan(0), reason: 'No tracks in: ${file.path}');
      }
    });
  });
}
