// Copyright 2025 The Pro Video Player Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_PIGEON_MESSAGES_H_
#define PIGEON_PIGEON_MESSAGES_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace pro_video_player {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Video source types supported by the platform.
enum class VideoSourceType {
  // Network video source (HTTP/HTTPS URL).
  kNetwork = 0,
  // Local file video source.
  kFile = 1,
  // Asset video source (bundled with the app).
  kAsset = 2
};

// Video scaling modes.
enum class VideoScalingModeEnum {
  // Fit the video within the view (letterbox/pillarbox).
  kFit = 0,
  // Fill the entire view (may crop video).
  kFill = 1,
  // Stretch the video to fill the view.
  kStretch = 2
};

// Subtitle render modes.
enum class SubtitleRenderModeEnum {
  // Auto-select best render mode.
  kAuto = 0,
  // Render subtitles natively.
  kNative = 1,
  // Render subtitles in Flutter.
  kFlutter = 2
};

// Controls mode.
enum class ControlsModeEnum {
  // Video only, no controls.
  kVideoOnly = 0,
  // Native platform controls.
  kNativeControls = 1,
  // Flutter controls.
  kFlutterControls = 2,
  // Custom controls.
  kCustomControls = 3
};

// Cast state.
enum class CastStateEnum {
  // Not connected to any cast device.
  kNotConnected = 0,
  // Connecting to cast device.
  kConnecting = 1,
  // Connected to cast device.
  kConnected = 2,
  // Disconnecting from cast device.
  kDisconnecting = 3
};

// Cast device type.
enum class CastDeviceTypeEnum {
  // AirPlay device.
  kAirPlay = 0,
  // Chromecast device.
  kChromecast = 1,
  // Web Remote Playback device.
  kWebRemotePlayback = 2,
  // Unknown device type.
  kUnknown = 3
};

// PiP action type.
enum class PipActionTypeEnum {
  // Play/pause toggle.
  kPlayPause = 0,
  // Skip to previous.
  kSkipPrevious = 1,
  // Skip to next.
  kSkipNext = 2,
  // Skip backward.
  kSkipBackward = 3,
  // Skip forward.
  kSkipForward = 4
};

// Subtitle format.
enum class SubtitleFormatEnum {
  // SRT format.
  kSrt = 0,
  // WebVTT format.
  kVtt = 1,
  // SSA format.
  kSsa = 2,
  // ASS format.
  kAss = 3,
  // TTML format.
  kTtml = 4
};

// Codec support level.
enum class CodecSupportLevelEnum {
  // Codec is fully supported.
  kSupported = 0,
  // Codec is probably supported.
  kProbablySupported = 1,
  // Codec is not supported.
  kNotSupported = 2,
  // Support status is unknown.
  kUnknown = 3
};

// Playback state enumeration.
enum class PlaybackStateEnum {
  // Player is uninitialized.
  kUninitialized = 0,
  // Player is initializing.
  kInitializing = 1,
  // Player is ready to play.
  kReady = 2,
  // Player is playing.
  kPlaying = 3,
  // Player is paused.
  kPaused = 4,
  // Playback has completed.
  kCompleted = 5,
  // Player is buffering.
  kBuffering = 6,
  // Player encountered an error.
  kError = 7,
  // Player has been disposed.
  kDisposed = 8
};


// Video source data passed to the platform.
//
// This represents the video source to be played. Only one of [url], [path],
// or [assetPath] should be set based on the [type].
//
// Generated class from Pigeon that represents data sent in messages.
class VideoSourceMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit VideoSourceMessage(const VideoSourceType& type);

  // Constructs an object setting all fields.
  explicit VideoSourceMessage(
    const VideoSourceType& type,
    const std::string* url,
    const std::string* path,
    const std::string* asset_path,
    const flutter::EncodableMap* headers);

  // The type of video source.
  const VideoSourceType& type() const;
  void set_type(const VideoSourceType& value_arg);

  // Network URL (for network sources).
  const std::string* url() const;
  void set_url(const std::string_view* value_arg);
  void set_url(std::string_view value_arg);

  // File path (for file sources).
  const std::string* path() const;
  void set_path(const std::string_view* value_arg);
  void set_path(std::string_view value_arg);

  // Asset path (for asset sources).
  const std::string* asset_path() const;
  void set_asset_path(const std::string_view* value_arg);
  void set_asset_path(std::string_view value_arg);

  // HTTP headers (for network sources).
  const flutter::EncodableMap* headers() const;
  void set_headers(const flutter::EncodableMap* value_arg);
  void set_headers(const flutter::EncodableMap& value_arg);


 private:
  static VideoSourceMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  VideoSourceType type_;
  std::optional<std::string> url_;
  std::optional<std::string> path_;
  std::optional<std::string> asset_path_;
  std::optional<flutter::EncodableMap> headers_;

};


// Video player options for initialization.
//
// Generated class from Pigeon that represents data sent in messages.
class VideoPlayerOptionsMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit VideoPlayerOptionsMessage(
    bool auto_play,
    bool looping,
    double volume,
    double playback_speed,
    bool allow_background_playback,
    bool mix_with_others,
    bool allow_pip,
    bool auto_enter_pip_on_background);

  // Constructs an object setting all fields.
  explicit VideoPlayerOptionsMessage(
    bool auto_play,
    bool looping,
    double volume,
    double playback_speed,
    const int64_t* start_position,
    const bool* enable_pip,
    const bool* enable_background_playback,
    const std::string* preferred_audio_language,
    const std::string* preferred_subtitle_language,
    const int64_t* max_bitrate,
    const int64_t* min_bitrate,
    const std::string* preferred_audio_rendition,
    bool allow_background_playback,
    bool mix_with_others,
    bool allow_pip,
    bool auto_enter_pip_on_background,
    const SubtitleRenderModeEnum* subtitle_render_mode,
    const bool* subtitles_enabled,
    const bool* show_subtitles_by_default);

  // Whether to start playing automatically after initialization.
  bool auto_play() const;
  void set_auto_play(bool value_arg);

  // Whether to loop the video.
  bool looping() const;
  void set_looping(bool value_arg);

  // Initial volume (0.0 to 1.0).
  double volume() const;
  void set_volume(double value_arg);

  // Initial playback speed.
  double playback_speed() const;
  void set_playback_speed(double value_arg);

  // Start position in milliseconds.
  const int64_t* start_position() const;
  void set_start_position(const int64_t* value_arg);
  void set_start_position(int64_t value_arg);

  // Whether to enable Picture-in-Picture mode.
  const bool* enable_pip() const;
  void set_enable_pip(const bool* value_arg);
  void set_enable_pip(bool value_arg);

  // Whether to enable background playback.
  const bool* enable_background_playback() const;
  void set_enable_background_playback(const bool* value_arg);
  void set_enable_background_playback(bool value_arg);

  // Preferred audio language code.
  const std::string* preferred_audio_language() const;
  void set_preferred_audio_language(const std::string_view* value_arg);
  void set_preferred_audio_language(std::string_view value_arg);

  // Preferred subtitle language code.
  const std::string* preferred_subtitle_language() const;
  void set_preferred_subtitle_language(const std::string_view* value_arg);
  void set_preferred_subtitle_language(std::string_view value_arg);

  // Maximum bitrate in bits per second.
  const int64_t* max_bitrate() const;
  void set_max_bitrate(const int64_t* value_arg);
  void set_max_bitrate(int64_t value_arg);

  // Minimum bitrate in bits per second.
  const int64_t* min_bitrate() const;
  void set_min_bitrate(const int64_t* value_arg);
  void set_min_bitrate(int64_t value_arg);

  // Preferred audio rendition name.
  const std::string* preferred_audio_rendition() const;
  void set_preferred_audio_rendition(const std::string_view* value_arg);
  void set_preferred_audio_rendition(std::string_view value_arg);

  // Whether to allow background playback (deprecated, use enableBackgroundPlayback).
  bool allow_background_playback() const;
  void set_allow_background_playback(bool value_arg);

  // Whether to mix audio with other apps.
  bool mix_with_others() const;
  void set_mix_with_others(bool value_arg);

  // Whether to allow Picture-in-Picture mode (deprecated, use enablePip).
  bool allow_pip() const;
  void set_allow_pip(bool value_arg);

  // Whether to auto-enter PiP when app goes to background.
  bool auto_enter_pip_on_background() const;
  void set_auto_enter_pip_on_background(bool value_arg);

  // The subtitle render mode for embedded subtitles.
  const SubtitleRenderModeEnum* subtitle_render_mode() const;
  void set_subtitle_render_mode(const SubtitleRenderModeEnum* value_arg);
  void set_subtitle_render_mode(const SubtitleRenderModeEnum& value_arg);

  // Whether subtitles are enabled.
  const bool* subtitles_enabled() const;
  void set_subtitles_enabled(const bool* value_arg);
  void set_subtitles_enabled(bool value_arg);

  // Whether to show subtitles by default when available.
  const bool* show_subtitles_by_default() const;
  void set_show_subtitles_by_default(const bool* value_arg);
  void set_show_subtitles_by_default(bool value_arg);


 private:
  static VideoPlayerOptionsMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  bool auto_play_;
  bool looping_;
  double volume_;
  double playback_speed_;
  std::optional<int64_t> start_position_;
  std::optional<bool> enable_pip_;
  std::optional<bool> enable_background_playback_;
  std::optional<std::string> preferred_audio_language_;
  std::optional<std::string> preferred_subtitle_language_;
  std::optional<int64_t> max_bitrate_;
  std::optional<int64_t> min_bitrate_;
  std::optional<std::string> preferred_audio_rendition_;
  bool allow_background_playback_;
  bool mix_with_others_;
  bool allow_pip_;
  bool auto_enter_pip_on_background_;
  std::optional<SubtitleRenderModeEnum> subtitle_render_mode_;
  std::optional<bool> subtitles_enabled_;
  std::optional<bool> show_subtitles_by_default_;

};


// Platform information returned by the platform.
//
// Contains static platform metadata that doesn't require async checks.
//
// Generated class from Pigeon that represents data sent in messages.
class PlatformInfoMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PlatformInfoMessage(
    const std::string& platform_name,
    const std::string& native_player_type);

  // Constructs an object setting all fields.
  explicit PlatformInfoMessage(
    const std::string& platform_name,
    const std::string& native_player_type,
    const flutter::EncodableMap* additional_info);

  // Platform name (e.g., "iOS", "Android", "Web").
  const std::string& platform_name() const;
  void set_platform_name(std::string_view value_arg);

  // Native player type (e.g., "AVPlayer", "ExoPlayer", "HTML5").
  const std::string& native_player_type() const;
  void set_native_player_type(std::string_view value_arg);

  // Additional platform-specific information as key-value pairs.
  //
  // May include:
  // - OS version
  // - SDK version
  // - Browser user agent
  // - Hardware capabilities
  const flutter::EncodableMap* additional_info() const;
  void set_additional_info(const flutter::EncodableMap* value_arg);
  void set_additional_info(const flutter::EncodableMap& value_arg);


 private:
  static PlatformInfoMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string platform_name_;
  std::string native_player_type_;
  std::optional<flutter::EncodableMap> additional_info_;

};


// Battery information.
//
// Generated class from Pigeon that represents data sent in messages.
class BatteryInfoMessage {
 public:
  // Constructs an object setting all fields.
  explicit BatteryInfoMessage(
    int64_t percentage,
    bool is_charging);

  // Battery percentage (0-100).
  int64_t percentage() const;
  void set_percentage(int64_t value_arg);

  // Whether the device is charging.
  bool is_charging() const;
  void set_is_charging(bool value_arg);


 private:
  static BatteryInfoMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t percentage_;
  bool is_charging_;

};


// Subtitle track information.
//
// Generated class from Pigeon that represents data sent in messages.
class SubtitleTrackMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit SubtitleTrackMessage(const std::string& id);

  // Constructs an object setting all fields.
  explicit SubtitleTrackMessage(
    const std::string& id,
    const std::string* label,
    const std::string* language,
    const SubtitleFormatEnum* format,
    const bool* is_default);

  // Track ID.
  const std::string& id() const;
  void set_id(std::string_view value_arg);

  // Track label.
  const std::string* label() const;
  void set_label(const std::string_view* value_arg);
  void set_label(std::string_view value_arg);

  // Track language code.
  const std::string* language() const;
  void set_language(const std::string_view* value_arg);
  void set_language(std::string_view value_arg);

  // Subtitle format.
  const SubtitleFormatEnum* format() const;
  void set_format(const SubtitleFormatEnum* value_arg);
  void set_format(const SubtitleFormatEnum& value_arg);

  // Whether this is the default track.
  const bool* is_default() const;
  void set_is_default(const bool* value_arg);
  void set_is_default(bool value_arg);


 private:
  static SubtitleTrackMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string id_;
  std::optional<std::string> label_;
  std::optional<std::string> language_;
  std::optional<SubtitleFormatEnum> format_;
  std::optional<bool> is_default_;

};


// Audio track information.
//
// Generated class from Pigeon that represents data sent in messages.
class AudioTrackMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit AudioTrackMessage(const std::string& id);

  // Constructs an object setting all fields.
  explicit AudioTrackMessage(
    const std::string& id,
    const std::string* label,
    const std::string* language,
    const int64_t* channel_count,
    const bool* is_default);

  // Track ID.
  const std::string& id() const;
  void set_id(std::string_view value_arg);

  // Track label.
  const std::string* label() const;
  void set_label(const std::string_view* value_arg);
  void set_label(std::string_view value_arg);

  // Track language code.
  const std::string* language() const;
  void set_language(const std::string_view* value_arg);
  void set_language(std::string_view value_arg);

  // Number of audio channels.
  const int64_t* channel_count() const;
  void set_channel_count(const int64_t* value_arg);
  void set_channel_count(int64_t value_arg);

  // Whether this is the default track.
  const bool* is_default() const;
  void set_is_default(const bool* value_arg);
  void set_is_default(bool value_arg);


 private:
  static AudioTrackMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string id_;
  std::optional<std::string> label_;
  std::optional<std::string> language_;
  std::optional<int64_t> channel_count_;
  std::optional<bool> is_default_;

};


// Video quality track information.
//
// Generated class from Pigeon that represents data sent in messages.
class VideoQualityTrackMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit VideoQualityTrackMessage(const std::string& id);

  // Constructs an object setting all fields.
  explicit VideoQualityTrackMessage(
    const std::string& id,
    const std::string* label,
    const int64_t* bitrate,
    const int64_t* width,
    const int64_t* height,
    const std::string* codec,
    const bool* is_default);

  // Track ID.
  const std::string& id() const;
  void set_id(std::string_view value_arg);

  // Track label.
  const std::string* label() const;
  void set_label(const std::string_view* value_arg);
  void set_label(std::string_view value_arg);

  // Bitrate in bits per second.
  const int64_t* bitrate() const;
  void set_bitrate(const int64_t* value_arg);
  void set_bitrate(int64_t value_arg);

  // Video width in pixels.
  const int64_t* width() const;
  void set_width(const int64_t* value_arg);
  void set_width(int64_t value_arg);

  // Video height in pixels.
  const int64_t* height() const;
  void set_height(const int64_t* value_arg);
  void set_height(int64_t value_arg);

  // Video codec.
  const std::string* codec() const;
  void set_codec(const std::string_view* value_arg);
  void set_codec(std::string_view value_arg);

  // Whether this is the default track.
  const bool* is_default() const;
  void set_is_default(const bool* value_arg);
  void set_is_default(bool value_arg);


 private:
  static VideoQualityTrackMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string id_;
  std::optional<std::string> label_;
  std::optional<int64_t> bitrate_;
  std::optional<int64_t> width_;
  std::optional<int64_t> height_;
  std::optional<std::string> codec_;
  std::optional<bool> is_default_;

};


// Picture-in-picture options.
//
// Generated class from Pigeon that represents data sent in messages.
class PipOptionsMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PipOptionsMessage(bool auto_enter_on_background);

  // Constructs an object setting all fields.
  explicit PipOptionsMessage(
    const double* aspect_ratio,
    bool auto_enter_on_background);

  // Aspect ratio (width / height).
  const double* aspect_ratio() const;
  void set_aspect_ratio(const double* value_arg);
  void set_aspect_ratio(double value_arg);

  // Auto-enter PiP when app goes to background.
  bool auto_enter_on_background() const;
  void set_auto_enter_on_background(bool value_arg);


 private:
  static PipOptionsMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<double> aspect_ratio_;
  bool auto_enter_on_background_;

};


// Picture-in-picture action.
//
// Generated class from Pigeon that represents data sent in messages.
class PipActionMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PipActionMessage(const PipActionTypeEnum& type);

  // Constructs an object setting all fields.
  explicit PipActionMessage(
    const PipActionTypeEnum& type,
    const std::string* title,
    const std::string* icon_name,
    const int64_t* skip_interval_ms);

  // Action type.
  const PipActionTypeEnum& type() const;
  void set_type(const PipActionTypeEnum& value_arg);

  // Action title.
  const std::string* title() const;
  void set_title(const std::string_view* value_arg);
  void set_title(std::string_view value_arg);

  // Icon name.
  const std::string* icon_name() const;
  void set_icon_name(const std::string_view* value_arg);
  void set_icon_name(std::string_view value_arg);

  // Optional skip interval in milliseconds.
  const int64_t* skip_interval_ms() const;
  void set_skip_interval_ms(const int64_t* value_arg);
  void set_skip_interval_ms(int64_t value_arg);


 private:
  static PipActionMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  PipActionTypeEnum type_;
  std::optional<std::string> title_;
  std::optional<std::string> icon_name_;
  std::optional<int64_t> skip_interval_ms_;

};


// Cast device information.
//
// Generated class from Pigeon that represents data sent in messages.
class CastDeviceMessage {
 public:
  // Constructs an object setting all fields.
  explicit CastDeviceMessage(
    const std::string& id,
    const std::string& name,
    const CastDeviceTypeEnum& type);

  // Device ID.
  const std::string& id() const;
  void set_id(std::string_view value_arg);

  // Device name.
  const std::string& name() const;
  void set_name(std::string_view value_arg);

  // Device type.
  const CastDeviceTypeEnum& type() const;
  void set_type(const CastDeviceTypeEnum& value_arg);


 private:
  static CastDeviceMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string id_;
  std::string name_;
  CastDeviceTypeEnum type_;

};


// Video metadata.
//
// Generated class from Pigeon that represents data sent in messages.
class VideoMetadataMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  VideoMetadataMessage();

  // Constructs an object setting all fields.
  explicit VideoMetadataMessage(
    const int64_t* duration,
    const int64_t* width,
    const int64_t* height,
    const std::string* video_codec,
    const std::string* audio_codec,
    const int64_t* bitrate,
    const double* frame_rate);

  // Duration in milliseconds.
  const int64_t* duration() const;
  void set_duration(const int64_t* value_arg);
  void set_duration(int64_t value_arg);

  // Video width in pixels.
  const int64_t* width() const;
  void set_width(const int64_t* value_arg);
  void set_width(int64_t value_arg);

  // Video height in pixels.
  const int64_t* height() const;
  void set_height(const int64_t* value_arg);
  void set_height(int64_t value_arg);

  // Video codec.
  const std::string* video_codec() const;
  void set_video_codec(const std::string_view* value_arg);
  void set_video_codec(std::string_view value_arg);

  // Audio codec.
  const std::string* audio_codec() const;
  void set_audio_codec(const std::string_view* value_arg);
  void set_audio_codec(std::string_view value_arg);

  // Bitrate in bits per second.
  const int64_t* bitrate() const;
  void set_bitrate(const int64_t* value_arg);
  void set_bitrate(int64_t value_arg);

  // Frame rate.
  const double* frame_rate() const;
  void set_frame_rate(const double* value_arg);
  void set_frame_rate(double value_arg);


 private:
  static VideoMetadataMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<int64_t> duration_;
  std::optional<int64_t> width_;
  std::optional<int64_t> height_;
  std::optional<std::string> video_codec_;
  std::optional<std::string> audio_codec_;
  std::optional<int64_t> bitrate_;
  std::optional<double> frame_rate_;

};


// Media metadata for platform controls.
//
// Generated class from Pigeon that represents data sent in messages.
class MediaMetadataMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  MediaMetadataMessage();

  // Constructs an object setting all fields.
  explicit MediaMetadataMessage(
    const std::string* title,
    const std::string* artist,
    const std::string* album,
    const std::string* artwork_url,
    const int64_t* duration);

  // Media title.
  const std::string* title() const;
  void set_title(const std::string_view* value_arg);
  void set_title(std::string_view value_arg);

  // Media artist/author.
  const std::string* artist() const;
  void set_artist(const std::string_view* value_arg);
  void set_artist(std::string_view value_arg);

  // Album name.
  const std::string* album() const;
  void set_album(const std::string_view* value_arg);
  void set_album(std::string_view value_arg);

  // Artwork URL.
  const std::string* artwork_url() const;
  void set_artwork_url(const std::string_view* value_arg);
  void set_artwork_url(std::string_view value_arg);

  // Duration in milliseconds.
  const int64_t* duration() const;
  void set_duration(const int64_t* value_arg);
  void set_duration(int64_t value_arg);


 private:
  static MediaMetadataMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> title_;
  std::optional<std::string> artist_;
  std::optional<std::string> album_;
  std::optional<std::string> artwork_url_;
  std::optional<int64_t> duration_;

};


// Subtitle source information.
//
// Generated class from Pigeon that represents data sent in messages.
class SubtitleSourceMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit SubtitleSourceMessage(
    const VideoSourceType& type,
    const std::string& path,
    bool is_default);

  // Constructs an object setting all fields.
  explicit SubtitleSourceMessage(
    const VideoSourceType& type,
    const std::string& path,
    const SubtitleFormatEnum* format,
    const std::string* label,
    const std::string* language,
    bool is_default,
    const std::string* webvtt_content);

  // Source type (network, file, asset).
  const VideoSourceType& type() const;
  void set_type(const VideoSourceType& value_arg);

  // Path or URL.
  const std::string& path() const;
  void set_path(std::string_view value_arg);

  // Subtitle format.
  const SubtitleFormatEnum* format() const;
  void set_format(const SubtitleFormatEnum* value_arg);
  void set_format(const SubtitleFormatEnum& value_arg);

  // Track label.
  const std::string* label() const;
  void set_label(const std::string_view* value_arg);
  void set_label(std::string_view value_arg);

  // Language code.
  const std::string* language() const;
  void set_language(const std::string_view* value_arg);
  void set_language(std::string_view value_arg);

  // Whether this is the default subtitle.
  bool is_default() const;
  void set_is_default(bool value_arg);

  // WebVTT content (for in-memory subtitles).
  const std::string* webvtt_content() const;
  void set_webvtt_content(const std::string_view* value_arg);
  void set_webvtt_content(std::string_view value_arg);


 private:
  static SubtitleSourceMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  VideoSourceType type_;
  std::string path_;
  std::optional<SubtitleFormatEnum> format_;
  std::optional<std::string> label_;
  std::optional<std::string> language_;
  bool is_default_;
  std::optional<std::string> webvtt_content_;

};


// External subtitle track information.
//
// Generated class from Pigeon that represents data sent in messages.
class ExternalSubtitleTrackMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ExternalSubtitleTrackMessage(
    const std::string& id,
    const std::string& label,
    bool is_default,
    const std::string& path,
    const std::string& source_type,
    const SubtitleFormatEnum& format);

  // Constructs an object setting all fields.
  explicit ExternalSubtitleTrackMessage(
    const std::string& id,
    const std::string& label,
    const std::string* language,
    bool is_default,
    const std::string& path,
    const std::string& source_type,
    const SubtitleFormatEnum& format);

  // Track ID.
  const std::string& id() const;
  void set_id(std::string_view value_arg);

  // Track label.
  const std::string& label() const;
  void set_label(std::string_view value_arg);

  // Track language code.
  const std::string* language() const;
  void set_language(const std::string_view* value_arg);
  void set_language(std::string_view value_arg);

  // Whether this is the default track.
  bool is_default() const;
  void set_is_default(bool value_arg);

  // Source path or URL.
  const std::string& path() const;
  void set_path(std::string_view value_arg);

  // Source type.
  const std::string& source_type() const;
  void set_source_type(std::string_view value_arg);

  // Subtitle format.
  const SubtitleFormatEnum& format() const;
  void set_format(const SubtitleFormatEnum& value_arg);


 private:
  static ExternalSubtitleTrackMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string id_;
  std::string label_;
  std::optional<std::string> language_;
  bool is_default_;
  std::string path_;
  std::string source_type_;
  SubtitleFormatEnum format_;

};


// Codec information for compatibility checking.
//
// Generated class from Pigeon that represents data sent in messages.
class CodecInfoMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit CodecInfoMessage(
    const std::string& fourcc,
    const std::string& name);

  // Constructs an object setting all fields.
  explicit CodecInfoMessage(
    const std::string& fourcc,
    const std::string& name,
    const std::string* codec_string,
    const std::string* mime_type);

  // Four character code (e.g., "avc1", "hvc1", "mp4a").
  const std::string& fourcc() const;
  void set_fourcc(std::string_view value_arg);

  // Human-readable codec name (e.g., "H.264", "HEVC", "AAC").
  const std::string& name() const;
  void set_name(std::string_view value_arg);

  // Full codec string including profile and level.
  const std::string* codec_string() const;
  void set_codec_string(const std::string_view* value_arg);
  void set_codec_string(std::string_view value_arg);

  // MIME type for the codec (e.g., "video/mp4", "audio/mp4").
  const std::string* mime_type() const;
  void set_mime_type(const std::string_view* value_arg);
  void set_mime_type(std::string_view value_arg);


 private:
  static CodecInfoMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class CodecCompatibilityMessage;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string fourcc_;
  std::string name_;
  std::optional<std::string> codec_string_;
  std::optional<std::string> mime_type_;

};


// Result of checking codec compatibility.
//
// Generated class from Pigeon that represents data sent in messages.
class CodecCompatibilityMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit CodecCompatibilityMessage(
    const CodecInfoMessage& codec,
    const CodecSupportLevelEnum& support_level);

  // Constructs an object setting all fields.
  explicit CodecCompatibilityMessage(
    const CodecInfoMessage& codec,
    const CodecSupportLevelEnum& support_level,
    const std::string* message,
    const std::string* minimum_os_version,
    const flutter::EncodableList* alternative_codecs);

  ~CodecCompatibilityMessage() = default;
  CodecCompatibilityMessage(const CodecCompatibilityMessage& other);
  CodecCompatibilityMessage& operator=(const CodecCompatibilityMessage& other);
  CodecCompatibilityMessage(CodecCompatibilityMessage&& other) = default;
  CodecCompatibilityMessage& operator=(CodecCompatibilityMessage&& other) noexcept = default;
  // The codec that was checked.
  const CodecInfoMessage& codec() const;
  void set_codec(const CodecInfoMessage& value_arg);

  // The level of support for this codec.
  const CodecSupportLevelEnum& support_level() const;
  void set_support_level(const CodecSupportLevelEnum& value_arg);

  // Human-readable message about the support status.
  const std::string* message() const;
  void set_message(const std::string_view* value_arg);
  void set_message(std::string_view value_arg);

  // Minimum OS version required for this codec.
  const std::string* minimum_os_version() const;
  void set_minimum_os_version(const std::string_view* value_arg);
  void set_minimum_os_version(std::string_view value_arg);

  // Alternative codecs that are supported.
  const flutter::EncodableList* alternative_codecs() const;
  void set_alternative_codecs(const flutter::EncodableList* value_arg);
  void set_alternative_codecs(const flutter::EncodableList& value_arg);


 private:
  static CodecCompatibilityMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::unique_ptr<CodecInfoMessage> codec_;
  CodecSupportLevelEnum support_level_;
  std::optional<std::string> message_;
  std::optional<std::string> minimum_os_version_;
  std::optional<flutter::EncodableList> alternative_codecs_;

};


// Video player event data sent from the platform to Dart.
//
// This is a base class for all events. Specific event types will include
// additional fields.
//
// Generated class from Pigeon that represents data sent in messages.
class VideoPlayerEventMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit VideoPlayerEventMessage(const std::string& type);

  // Constructs an object setting all fields.
  explicit VideoPlayerEventMessage(
    const std::string& type,
    const PlaybackStateEnum* state,
    const int64_t* position_ms,
    const int64_t* buffered_position_ms,
    const int64_t* duration_ms,
    const std::string* error_message,
    const std::string* error_code,
    const int64_t* width,
    const int64_t* height);

  // The type of event.
  const std::string& type() const;
  void set_type(std::string_view value_arg);

  // Playback state (for playbackStateChanged events).
  const PlaybackStateEnum* state() const;
  void set_state(const PlaybackStateEnum* value_arg);
  void set_state(const PlaybackStateEnum& value_arg);

  // Position in milliseconds (for positionChanged events).
  const int64_t* position_ms() const;
  void set_position_ms(const int64_t* value_arg);
  void set_position_ms(int64_t value_arg);

  // Buffered position in milliseconds (for bufferedPositionChanged events).
  const int64_t* buffered_position_ms() const;
  void set_buffered_position_ms(const int64_t* value_arg);
  void set_buffered_position_ms(int64_t value_arg);

  // Duration in milliseconds (for durationChanged events).
  const int64_t* duration_ms() const;
  void set_duration_ms(const int64_t* value_arg);
  void set_duration_ms(int64_t value_arg);

  // Error message (for error events).
  const std::string* error_message() const;
  void set_error_message(const std::string_view* value_arg);
  void set_error_message(std::string_view value_arg);

  // Error code (for error events).
  const std::string* error_code() const;
  void set_error_code(const std::string_view* value_arg);
  void set_error_code(std::string_view value_arg);

  // Video width (for videoSizeChanged events).
  const int64_t* width() const;
  void set_width(const int64_t* value_arg);
  void set_width(int64_t value_arg);

  // Video height (for videoSizeChanged events).
  const int64_t* height() const;
  void set_height(const int64_t* value_arg);
  void set_height(int64_t value_arg);


 private:
  static VideoPlayerEventMessage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ProVideoPlayerHostApi;
  friend class ProVideoPlayerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string type_;
  std::optional<PlaybackStateEnum> state_;
  std::optional<int64_t> position_ms_;
  std::optional<int64_t> buffered_position_ms_;
  std::optional<int64_t> duration_ms_;
  std::optional<std::string> error_message_;
  std::optional<std::string> error_code_;
  std::optional<int64_t> width_;
  std::optional<int64_t> height_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Host API for video player platform methods.
//
// This API is implemented on the native platform (iOS, Android, etc.)
// and called from Dart.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class ProVideoPlayerHostApi {
 public:
  ProVideoPlayerHostApi(const ProVideoPlayerHostApi&) = delete;
  ProVideoPlayerHostApi& operator=(const ProVideoPlayerHostApi&) = delete;
  virtual ~ProVideoPlayerHostApi() {}
  // Creates a new video player instance with the given source and options.
  //
  // Returns the player ID that should be used for all subsequent operations.
  virtual void Create(
    const VideoSourceMessage& source,
    const VideoPlayerOptionsMessage& options,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  // Disposes a video player instance.
  virtual void Dispose(
    int64_t player_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Starts playback.
  virtual void Play(
    int64_t player_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Pauses playback.
  virtual void Pause(
    int64_t player_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Stops playback.
  virtual void Stop(
    int64_t player_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Seeks to the specified position.
  //
  // [positionMs] is the position in milliseconds.
  virtual void SeekTo(
    int64_t player_id,
    int64_t position_ms,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Sets the playback speed.
  virtual void SetPlaybackSpeed(
    int64_t player_id,
    double speed,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Sets the volume (0.0 to 1.0).
  virtual void SetVolume(
    int64_t player_id,
    double volume,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Gets the current playback position in milliseconds.
  virtual void GetPosition(
    int64_t player_id,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  // Gets the video duration in milliseconds.
  virtual void GetDuration(
    int64_t player_id,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  // Gets static platform information.
  virtual void GetPlatformInfo(std::function<void(ErrorOr<PlatformInfoMessage> reply)> result) = 0;
  // Enables or disables verbose logging.
  virtual void SetVerboseLogging(
    bool enabled,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Checks if Picture-in-Picture mode is supported.
  virtual void SupportsPictureInPicture(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if fullscreen mode is supported.
  virtual void SupportsFullscreen(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if background playback is supported.
  virtual void SupportsBackgroundPlayback(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if any form of casting is supported.
  virtual void SupportsCasting(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if AirPlay is supported.
  virtual void SupportsAirPlay(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if Chromecast is supported.
  virtual void SupportsChromecast(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if Remote Playback API is supported.
  virtual void SupportsRemotePlayback(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if quality selection is supported.
  virtual void SupportsQualitySelection(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if playback speed control is supported.
  virtual void SupportsPlaybackSpeedControl(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if subtitles are supported.
  virtual void SupportsSubtitles(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if external subtitles are supported.
  virtual void SupportsExternalSubtitles(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if audio track selection is supported.
  virtual void SupportsAudioTrackSelection(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if chapters are supported.
  virtual void SupportsChapters(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if video metadata extraction is supported.
  virtual void SupportsVideoMetadataExtraction(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if network monitoring is supported.
  virtual void SupportsNetworkMonitoring(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if bandwidth estimation is supported.
  virtual void SupportsBandwidthEstimation(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if adaptive bitrate streaming is supported.
  virtual void SupportsAdaptiveBitrate(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if HLS is supported.
  virtual void SupportsHLS(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if DASH is supported.
  virtual void SupportsDASH(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if device volume control is supported.
  virtual void SupportsDeviceVolumeControl(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if screen brightness control is supported.
  virtual void SupportsScreenBrightnessControl(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Gets the device volume (0.0 to 1.0).
  virtual void GetDeviceVolume(std::function<void(ErrorOr<double> reply)> result) = 0;
  // Sets the device volume (0.0 to 1.0).
  virtual void SetDeviceVolume(
    double volume,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Gets the screen brightness (0.0 to 1.0).
  virtual void GetScreenBrightness(std::function<void(ErrorOr<double> reply)> result) = 0;
  // Sets the screen brightness (0.0 to 1.0).
  virtual void SetScreenBrightness(
    double brightness,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Gets the current battery info.
  virtual void GetBatteryInfo(std::function<void(ErrorOr<std::optional<BatteryInfoMessage>> reply)> result) = 0;
  // Sets whether the video should loop.
  virtual void SetLooping(
    int64_t player_id,
    bool looping,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Sets the video scaling mode.
  virtual void SetScalingMode(
    int64_t player_id,
    const VideoScalingModeEnum& mode,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Sets the controls mode.
  virtual void SetControlsMode(
    int64_t player_id,
    const ControlsModeEnum& mode,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Sets the active subtitle track.
  virtual void SetSubtitleTrack(
    int64_t player_id,
    const SubtitleTrackMessage* track,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Sets the subtitle render mode.
  virtual void SetSubtitleRenderMode(
    int64_t player_id,
    const SubtitleRenderModeEnum& mode,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Adds an external subtitle file.
  virtual void AddExternalSubtitle(
    int64_t player_id,
    const SubtitleSourceMessage& source,
    std::function<void(ErrorOr<std::optional<ExternalSubtitleTrackMessage>> reply)> result) = 0;
  // Removes an external subtitle track.
  virtual void RemoveExternalSubtitle(
    int64_t player_id,
    const std::string& track_id,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Gets all external subtitle tracks.
  virtual void GetExternalSubtitles(
    int64_t player_id,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  // Sets the active audio track.
  virtual void SetAudioTrack(
    int64_t player_id,
    const AudioTrackMessage* track,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Enters picture-in-picture mode.
  virtual void EnterPip(
    int64_t player_id,
    const PipOptionsMessage& options,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Exits picture-in-picture mode.
  virtual void ExitPip(
    int64_t player_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Checks if PiP is supported on this platform.
  virtual void IsPipSupported(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Sets the actions available in PiP mode.
  virtual void SetPipActions(
    int64_t player_id,
    const flutter::EncodableList& actions,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Enters fullscreen mode.
  virtual void EnterFullscreen(
    int64_t player_id,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Exits fullscreen mode.
  virtual void ExitFullscreen(
    int64_t player_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Sets window fullscreen state (desktop platforms).
  virtual void SetWindowFullscreen(
    bool fullscreen,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Enables or disables background playback.
  virtual void SetBackgroundPlayback(
    int64_t player_id,
    bool enabled,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Checks if background playback is supported.
  virtual void IsBackgroundPlaybackSupported(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Gets available video quality tracks.
  virtual void GetVideoQualities(
    int64_t player_id,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  // Sets the video quality track.
  virtual void SetVideoQuality(
    int64_t player_id,
    const VideoQualityTrackMessage& track,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Gets the current video quality track.
  virtual void GetCurrentVideoQuality(
    int64_t player_id,
    std::function<void(ErrorOr<VideoQualityTrackMessage> reply)> result) = 0;
  // Checks if quality selection is supported.
  virtual void IsQualitySelectionSupported(
    int64_t player_id,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Gets video metadata.
  virtual void GetVideoMetadata(
    int64_t player_id,
    std::function<void(ErrorOr<std::optional<VideoMetadataMessage>> reply)> result) = 0;
  // Sets media metadata for platform controls.
  virtual void SetMediaMetadata(
    int64_t player_id,
    const MediaMetadataMessage& metadata,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Checks if casting is supported on this platform.
  virtual void IsCastingSupported(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Gets available cast devices.
  virtual void GetAvailableCastDevices(
    int64_t player_id,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  // Starts casting to a device.
  virtual void StartCasting(
    int64_t player_id,
    const CastDeviceMessage* device,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Stops casting.
  virtual void StopCasting(
    int64_t player_id,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Gets the current cast state.
  virtual void GetCastState(
    int64_t player_id,
    std::function<void(ErrorOr<CastStateEnum> reply)> result) = 0;
  // Gets the current cast device.
  virtual void GetCurrentCastDevice(
    int64_t player_id,
    std::function<void(ErrorOr<std::optional<CastDeviceMessage>> reply)> result) = 0;
  // Checks if a specific codec is supported on this platform.
  //
  // Uses platform-specific APIs:
  // - Web: MediaSource.isTypeSupported() / HTMLMediaElement.canPlayType()
  // - iOS/macOS: AVURLAsset.isPlayableExtendedMIMEType()
  // - Android: MediaCodecList.findDecoderForFormat()
  //
  // The [codec] parameter should include the fourcc and optionally
  // the full codec string for more accurate checking.
  virtual void CheckCodecSupport(
    const CodecInfoMessage& codec,
    std::function<void(ErrorOr<CodecCompatibilityMessage> reply)> result) = 0;
  // Checks if multiple codecs are supported on this platform.
  //
  // More efficient than calling [checkCodecSupport] multiple times
  // as it may batch platform API calls.
  virtual void CheckCodecsSupport(
    const flutter::EncodableList& codecs,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  // Gets a list of codecs that are guaranteed to be supported.
  //
  // Returns the platform's baseline supported codecs:
  // - Common video codecs (H.264, potentially HEVC)
  // - Common audio codecs (AAC, MP3)
  //
  // This can be used to suggest transcoding options when
  // a file contains unsupported codecs.
  virtual void GetSupportedCodecs(std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;

  // The codec used by ProVideoPlayerHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `ProVideoPlayerHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    ProVideoPlayerHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    ProVideoPlayerHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  ProVideoPlayerHostApi() = default;

};
// Flutter API for callbacks from the platform to Dart.
//
// This API is implemented in Dart and called from the native platform
// to send events.
//
// HYBRID EVENT SYSTEM:
// - High-frequency events (position, buffering, state) use EventChannel
// - Low-frequency events (errors, metadata, completion) use @FlutterApi for type safety
//
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class ProVideoPlayerFlutterApi {
 public:
  ProVideoPlayerFlutterApi(flutter::BinaryMessenger* binary_messenger);
  ProVideoPlayerFlutterApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  // Called when a video player event occurs (deprecated - kept for EventChannel compatibility).
  //
  // High-frequency events still use EventChannel:
  // - positionChanged, bufferedPositionChanged
  // - playbackStateChanged, durationChanged
  // - videoSizeChanged, bufferingStarted, bufferingEnded
  void OnEvent(
    int64_t player_id,
    const VideoPlayerEventMessage& event,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Called when an error occurs during playback.
  void OnError(
    int64_t player_id,
    const std::string& error_code,
    const std::string& error_message,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Called when video metadata is extracted.
  void OnMetadataExtracted(
    int64_t player_id,
    const VideoMetadataMessage& metadata,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Called when playback completes.
  void OnPlaybackCompleted(
    int64_t player_id,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Called when a PiP action is triggered by the user.
  void OnPipActionTriggered(
    int64_t player_id,
    const std::string& action,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Called when cast state changes.
  void OnCastStateChanged(
    int64_t player_id,
    const CastStateEnum& state,
    const CastDeviceMessage* device,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Called when subtitle tracks change.
  void OnSubtitleTracksChanged(
    int64_t player_id,
    const flutter::EncodableList& tracks,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Called when audio tracks change.
  void OnAudioTracksChanged(
    int64_t player_id,
    const flutter::EncodableList& tracks,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  // Called when battery information changes.
  //
  // Emitted when the device's battery level or charging state changes.
  // Platform availability varies (see getBatteryInfo documentation).
  void OnBatteryInfoChanged(
    const BatteryInfoMessage& battery_info,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace pro_video_player
#endif  // PIGEON_PIGEON_MESSAGES_H_
